language: node_js
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq golang php5-cli ruby python pylint
 - npm install -g jshint coffeelint jsonlint js-yaml eslint htmlhint
script: htmlhint